### ISSUE TITLE
Ayuda mi tilina

### ISSUE THREAD

**Issue by themqrs** [alanfzf/mqrs-top-img-gen#2]
Hola tilina, era sobre el bot del top. Que actualmente te pide que las notas esten en el intervalo del 0 al 10, pero antes se podia dejar en blanco y salia como la img

Asi que quiero que vuelva como el pasado, pq siempre el pasado es mejor 
Snowy > Closer
Pedru > Oswaldo 
![c305c290-1bc9-412d-a6e2-48388c3ebac4](https://github.com/alanfvn/mqrs-top-img-gen/assets/141203609/1559ad88-cd9e-49b5-952f-933560fc396e)

**Comment by alanfzf** [comment]
Arreglado #3 
![Dr _Stone_New_World_1](https://github.com/alanfzf/mqrs-top-img-gen/assets/29936954/5742fb36-b952-4beb-a288-6bdfa642e4ca)
